-- =============================================================================
--  水化管理 —— Oracle 資料表設計（完整範例）
-- =============================================================================
--
--  對應頁面：/pages/hydration/wafer.php
--  對應程式：app/Domain/Hydration/
--
--  這一份是「可以直接照著建、也可以照著改」的參考。每一個索引、每一個
--  唯一鍵下面都寫了「為什麼要有它」——現場資料出問題的時候，多半是因為
--  某個唯一鍵當初沒建。
--
--  版本相容：語法以 Oracle 11g 為底（現場最常見的版本），
--  12c 以後可以用的更短寫法寫在註解裡。
--
--  執行順序：資料表 → 索引 → 序號 → 順序表 → 註解
-- =============================================================================


-- -----------------------------------------------------------------------------
-- 1. 水化紀錄（主表）
-- -----------------------------------------------------------------------------
--  一列 = 某一個乾片批號的某一次水化。
--  同一個乾片批號會水化好幾次，所以「乾片批號」不是主鍵。
-- -----------------------------------------------------------------------------
CREATE TABLE MES_HYD_WAFER (
    HYD_ID           NUMBER(12)    NOT NULL,     -- 流水號（代理鍵）
    HYD_DATE         DATE          NOT NULL,     -- 日期（水化日，只到日，不存時分秒）
    QTY              NUMBER(7)     NOT NULL,     -- 數量（片）
    DRY_LOT_NO       VARCHAR2(30)  NOT NULL,     -- 乾片批號
    HYD_DAY_CODE     VARCHAR2(6)   NOT NULL,     -- 水化日編號
    PACK_LOT_NO      VARCHAR2(40),               -- 封包批號（正式：封包完成後才有）
    HYD_SEQ          NUMBER(2)     NOT NULL,     -- 第幾次水化（1 開始）
    PRE_PACK_LOT_NO  VARCHAR2(40),               -- 預配封包批號（對外 API 取號後寫回）
    SOURCE           VARCHAR2(10)  DEFAULT 'IMPORT' NOT NULL,   -- IMPORT / API
    CREATED_AT       DATE          DEFAULT SYSDATE NOT NULL,
    UPDATED_AT       DATE          DEFAULT SYSDATE NOT NULL,

    CONSTRAINT PK_HYD_WAFER PRIMARY KEY (HYD_ID),

    -- 同一個乾片批號的同一次水化只能有一列。
    -- 匯入時的「第幾次水化不可以重複」檢查是在程式裡做的（為了給使用者
    -- 看得懂的訊息），但這個唯一鍵是最後一道防線：程式有 bug、有人手動
    -- 塞資料、兩支匯入同時跑，都還是進不去。
    -- 欄位順序是 (乾片批號, 第幾次)，因為查詢一律是「這個乾片批號的水化歷程」，
    -- 反過來寫的話那種查詢就用不到索引。
    CONSTRAINT UX_HYD_WAFER_LOT_SEQ UNIQUE (DRY_LOT_NO, HYD_SEQ),

    -- 預配封包批號不可重複。
    -- 這是取號併發的最後一道防線 —— Oracle 的唯一索引不管「全部欄位都是
    -- NULL」的列，所以還沒取號的幾萬列不會互相衝突，也不會進索引佔空間。
    CONSTRAINT UX_HYD_WAFER_PRE_PACK UNIQUE (PRE_PACK_LOT_NO),

    CONSTRAINT CK_HYD_WAFER_QTY CHECK (QTY > 0),
    CONSTRAINT CK_HYD_WAFER_SEQ CHECK (HYD_SEQ BETWEEN 1 AND 99),
    CONSTRAINT CK_HYD_WAFER_SRC CHECK (SOURCE IN ('IMPORT', 'API', 'MANUAL'))
);

-- 頁面預設的查法是「日期區間 + 條件」，所以日期放索引第一欄。
-- 第二欄放乾片批號，是為了讓「某天某批」這種查詢在索引裡就找完，
-- 不用再回表（covering 的效果）。
CREATE INDEX IX_HYD_WAFER_DATE ON MES_HYD_WAFER (HYD_DATE, DRY_LOT_NO);

-- 依水化日編號查（現場拿著一張水化日報表來對數字時用這個）
CREATE INDEX IX_HYD_WAFER_DAY  ON MES_HYD_WAFER (HYD_DAY_CODE, HYD_DATE);

-- 依封包批號回查是哪一批乾片（出貨端問「這箱是哪批」時用這個）
CREATE INDEX IX_HYD_WAFER_PACK ON MES_HYD_WAFER (PACK_LOT_NO);

-- 「還沒封包的有哪些」是頁面上的一個勾選條件，也是取號 API 每次都要找的東西。
-- 用 function-based index 只把「還沒封包」的那些列放進索引：
-- 資料放久了以後，未封包的永遠只有幾百列，索引就一直很小。
--
-- ⚠ 用這個索引的查詢條件必須寫成完全一樣的運算式，例如
--     WHERE CASE WHEN PACK_LOT_NO IS NULL THEN DRY_LOT_NO END = :dry_lot_no
--   直接寫 WHERE PACK_LOT_NO IS NULL AND DRY_LOT_NO = :x 是用不到它的。
--   本模板的程式沒有用這種寫法（可讀性優先），所以這個索引先註解起來，
--   等資料量真的大到有感再開。
--
-- CREATE INDEX IX_HYD_WAFER_OPEN ON MES_HYD_WAFER
--     (CASE WHEN PACK_LOT_NO IS NULL THEN DRY_LOT_NO END);

CREATE SEQUENCE MES_HYD_WAFER_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
-- NOCACHE：現場常常要「照號碼順序」看資料，CACHE 在資料庫重啟後會跳號。
-- 資料量很大（每天上萬筆）時改成 CACHE 20 會快一些，代價就是跳號。
--
-- 12c 以後可以省掉這個序號，直接寫：
--   HYD_ID NUMBER GENERATED BY DEFAULT AS IDENTITY


-- -----------------------------------------------------------------------------
-- 2. 封包批號的當日順序
-- -----------------------------------------------------------------------------
--  一天一列。取號的時候鎖這一列，所以同一天的取號會排隊、不同天不互相影響。
--
--  為什麼不用 SEQUENCE：
--    - SEQUENCE 是全域的，沒辦法「每天從 01 重新開始」
--    - NEXTVAL 不受交易保護，rollback 之後號碼就是跳掉了（現場會問為什麼少一號）
--    - 我們的順序不是 +1 而是 01 → 04 → 07 …（步進值 3），SEQUENCE 也表達不了
--
--  為什麼不用 SELECT MAX(順序) + 1：
--    兩支同時進來會算出同一個號碼。加上唯一索引雖然擋得住，但變成「撞了再重試」，
--    高併發時重試會越來越多。鎖一列的成本反而更低、行為也可預測。
-- -----------------------------------------------------------------------------
CREATE TABLE MES_HYD_PACK_SEQ (
    DAY_CODE    VARCHAR2(6) NOT NULL,                    -- 水化日編號
    NEXT_VAL    NUMBER(4)   DEFAULT 1 NOT NULL,          -- 下一個要發出去的順序值（1, 4, 7 …）
    UPDATED_AT  DATE        DEFAULT SYSDATE NOT NULL,

    CONSTRAINT PK_HYD_PACK_SEQ PRIMARY KEY (DAY_CODE),
    CONSTRAINT CK_HYD_PACK_SEQ CHECK (NEXT_VAL >= 1)
);


-- -----------------------------------------------------------------------------
-- 3. 取號的完整流程（對外 API 進來時跑這一段）
-- -----------------------------------------------------------------------------
--  程式碼在 app/Domain/Hydration/PackLotService.php，這裡列出它實際送出的 SQL。
--
--  封包批號 = 乾片批號去掉後 5 碼 + 水化日編號 + 當日順序（2 碼）
--             DRY-A2408- + H0812  +  01
--          => DRY-A2408-H081201
--
--  順序：01 → 04 → 07 → 10 → 13 → 16 → 19 → 20 → 23 …（每一段只用 0/3/6/9）
--        十位數用完 9 之後換英文字母：… 96 → 99 → A0 → A3 → A6 → A9 → B0 …
--        （步進值與編碼規則寫在 config/app.php 的 hydration，可以改）
--
--  鎖的順序固定「先鎖水化紀錄那一列、再鎖當日順序那一列」。
--  兩支程式用相反順序鎖同樣兩列就會 deadlock，所以這件事要寫下來。
-- -----------------------------------------------------------------------------

-- 3-1 找出並鎖住這個乾片批號「最新一次水化」那一列。
--     WAIT 3：等最多三秒。等不到就回「系統忙碌中請重試」給呼叫端，
--     不要讓對方的連線一直掛在那裡（NOWAIT 太急、無限等最糟）。
--
--     SELECT ... FOR UPDATE 的鎖會一直持有到 COMMIT，
--     所以這個交易裡面絕對不可以做檔案解析、呼叫別的系統這類慢動作。
/*
SELECT HYD_ID, DRY_LOT_NO, HYD_DAY_CODE, PACK_LOT_NO, PRE_PACK_LOT_NO
  FROM MES_HYD_WAFER
 WHERE DRY_LOT_NO = :dry_lot_no
   AND HYD_SEQ = (SELECT MAX(HYD_SEQ) FROM MES_HYD_WAFER WHERE DRY_LOT_NO = :dry_lot_no)
   FOR UPDATE WAIT 3;

-- 3-2 已經有預配封包批號 => 原號回傳，不要再燒一個號。
--     呼叫端重試、網路斷線重送都會走到這裡，所以這支 API 是可以重複呼叫的
--     （idempotent）。少了這一步，對方重試一次就多一個號、數量就對不起來。

-- 3-3 鎖住當日順序那一列，沒有就先建一列。
--     ORA-00001（唯一鍵衝突）表示別人剛好也在建，重新 SELECT 一次就好。
SELECT NEXT_VAL FROM MES_HYD_PACK_SEQ WHERE DAY_CODE = :day_code FOR UPDATE WAIT 3;

INSERT INTO MES_HYD_PACK_SEQ (DAY_CODE, NEXT_VAL) VALUES (:day_code, 1);

-- 3-4 把順序往前推。
--     下一個值是程式算好再帶進來的（PackLotNumber::next()），不是在 SQL 裡 +3 ——
--     進位規則（A9 的下一個是 B0 還是 B2）只能有一個地方說了算。
UPDATE MES_HYD_PACK_SEQ
   SET NEXT_VAL = :next_val, UPDATED_AT = SYSDATE
 WHERE DAY_CODE = :day_code;

-- 3-5 寫回那一列的預配封包批號。
--     WHERE 多一個 PRE_PACK_LOT_NO IS NULL：萬一鎖沒鎖到（有人繞過流程、
--     或程式改壞了），這一句也不會蓋掉別人已經寫進去的號碼。
--     更新到 0 列就表示發生了這件事 —— 重新讀一次、把既有的號碼回傳。
UPDATE MES_HYD_WAFER
   SET PRE_PACK_LOT_NO = :pre_pack_lot_no,
       UPDATED_AT      = SYSDATE
 WHERE HYD_ID          = :hyd_id
   AND PRE_PACK_LOT_NO IS NULL;

COMMIT;
*/


-- -----------------------------------------------------------------------------
-- 4. 匯入時的寫入（MERGE：有就更新、沒有就新增）
-- -----------------------------------------------------------------------------
--  比對鍵是 (DRY_LOT_NO, HYD_SEQ)，跟唯一鍵一致。
--
--  「已經封包的那一次水化不可以被覆蓋」這條規則在程式裡先檢查過了
--  （才能告訴使用者是第幾列、為什麼不行），這裡的 WHERE PACK_LOT_NO IS NULL
--  是第二道防線：從檢查到寫入之間，別人可能剛好把它封包了。
--
--  ⚠ 同一個具名參數在 Oracle 只能出現一次，所以 INSERT 那段要另外取名（_ins）。
-- -----------------------------------------------------------------------------
/*
MERGE INTO MES_HYD_WAFER t
USING (SELECT :dry_lot_no AS DRY_LOT_NO, :hyd_seq AS HYD_SEQ FROM DUAL) s
   ON (t.DRY_LOT_NO = s.DRY_LOT_NO AND t.HYD_SEQ = s.HYD_SEQ)
WHEN MATCHED THEN
    UPDATE SET t.HYD_DATE     = TO_DATE(:hyd_date, 'YYYY-MM-DD'),
               t.QTY          = :qty,
               t.HYD_DAY_CODE = :hyd_day_code,
               t.UPDATED_AT   = SYSDATE
     WHERE t.PACK_LOT_NO IS NULL
WHEN NOT MATCHED THEN
    INSERT (HYD_ID, HYD_DATE, QTY, DRY_LOT_NO, HYD_DAY_CODE, HYD_SEQ, SOURCE, CREATED_AT, UPDATED_AT)
    VALUES (MES_HYD_WAFER_SEQ.NEXTVAL, TO_DATE(:hyd_date_ins, 'YYYY-MM-DD'), :qty_ins,
            :dry_lot_no_ins, :hyd_day_code_ins, :hyd_seq_ins, 'IMPORT', SYSDATE, SYSDATE);
*/


-- -----------------------------------------------------------------------------
-- 5. 註解（現場自己開 SQL 工具看資料時，靠這些看懂欄位）
-- -----------------------------------------------------------------------------
COMMENT ON TABLE  MES_HYD_WAFER                  IS '水化紀錄：一列 = 某乾片批號的某一次水化';
COMMENT ON COLUMN MES_HYD_WAFER.HYD_DATE         IS '日期（水化日）';
COMMENT ON COLUMN MES_HYD_WAFER.QTY              IS '數量（片）';
COMMENT ON COLUMN MES_HYD_WAFER.DRY_LOT_NO       IS '乾片批號';
COMMENT ON COLUMN MES_HYD_WAFER.HYD_DAY_CODE     IS '水化日編號，封包批號的中段';
COMMENT ON COLUMN MES_HYD_WAFER.PACK_LOT_NO      IS '封包批號（正式，封包完成後才有）';
COMMENT ON COLUMN MES_HYD_WAFER.HYD_SEQ          IS '第幾次水化，同一乾片批號從 1 開始且必須連號';
COMMENT ON COLUMN MES_HYD_WAFER.PRE_PACK_LOT_NO  IS '預配封包批號：對外 API 取號後寫回，尚未完成封包';
COMMENT ON COLUMN MES_HYD_WAFER.SOURCE           IS '資料來源：IMPORT 匯入 / API 對外介接 / MANUAL 人工';

COMMENT ON TABLE  MES_HYD_PACK_SEQ               IS '封包批號當日順序：一天一列，取號時鎖這一列';
COMMENT ON COLUMN MES_HYD_PACK_SEQ.DAY_CODE      IS '水化日編號';
COMMENT ON COLUMN MES_HYD_PACK_SEQ.NEXT_VAL      IS '下一個要發出去的順序值（1、4、7 …）';


-- -----------------------------------------------------------------------------
-- 6. 頁面實際會送出的兩句查詢（附上預期用到的索引）
-- -----------------------------------------------------------------------------
--  查明細（走 IX_HYD_WAFER_DATE）：
/*
SELECT w.HYD_ID, w.HYD_DATE, w.QTY, w.DRY_LOT_NO, w.HYD_DAY_CODE,
       w.PACK_LOT_NO, w.HYD_SEQ, w.PRE_PACK_LOT_NO
  FROM MES_HYD_WAFER w
 WHERE w.HYD_DATE >= TO_DATE(:start_date, 'YYYY-MM-DD')
   AND w.HYD_DATE <  TO_DATE(:end_date, 'YYYY-MM-DD') + 1
 ORDER BY w.HYD_DATE DESC, w.DRY_LOT_NO, w.HYD_SEQ;
*/
--  ⚠ 日期條件不要寫成 TRUNC(w.HYD_DATE) = :d，那樣索引就用不到了。
--    要嘛照上面寫成區間，要嘛替 TRUNC(HYD_DATE) 另外建 function-based index。
--
--  今日統整（走 IX_HYD_WAFER_DATE，只掃當天那一段）。
--  COUNT(欄位) 只算「不是 NULL」的那些列，COUNT(*) 才是全部，
--  所以「已封包幾筆」不需要寫成 SUM(CASE WHEN … THEN 1 ELSE 0 END)：
/*
SELECT COUNT(*)                     AS row_cnt,      -- 總筆數
       SUM(w.QTY)                   AS qty_sum,      -- 總數量
       COUNT(DISTINCT w.DRY_LOT_NO) AS lot_cnt,      -- 幾個乾片批號
       COUNT(w.PACK_LOT_NO)         AS packed_cnt,   -- 已封包（未封包 = row_cnt - packed_cnt）
       COUNT(w.PRE_PACK_LOT_NO)     AS pre_cnt       -- 已取號
  FROM MES_HYD_WAFER w
 WHERE w.HYD_DATE >= TRUNC(SYSDATE)
   AND w.HYD_DATE <  TRUNC(SYSDATE) + 1;
*/


-- -----------------------------------------------------------------------------
-- 7. 幾筆測試資料（照著這個長相就對了）
-- -----------------------------------------------------------------------------
/*
INSERT INTO MES_HYD_WAFER (HYD_ID, HYD_DATE, QTY, DRY_LOT_NO, HYD_DAY_CODE,
                           PACK_LOT_NO, HYD_SEQ, PRE_PACK_LOT_NO, SOURCE)
VALUES (MES_HYD_WAFER_SEQ.NEXTVAL, TRUNC(SYSDATE), 1200, 'DRY-A2408-10001', 'H0812',
        'DRY-A2408-H081201', 1, 'DRY-A2408-H081201', 'IMPORT');

INSERT INTO MES_HYD_WAFER (HYD_ID, HYD_DATE, QTY, DRY_LOT_NO, HYD_DAY_CODE,
                           PACK_LOT_NO, HYD_SEQ, PRE_PACK_LOT_NO, SOURCE)
VALUES (MES_HYD_WAFER_SEQ.NEXTVAL, TRUNC(SYSDATE), 980, 'DRY-A2408-10001', 'H0812',
        NULL, 2, NULL, 'IMPORT');

INSERT INTO MES_HYD_PACK_SEQ (DAY_CODE, NEXT_VAL) VALUES ('H0812', 4);

COMMIT;
*/
